//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.11.01 at 04:22:12 PM IST
//


package com.knack.jaxbClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "firstName", "lastName", "city", "country" })
@XmlRootElement(name = "Employee")
public class Employee
{

	@XmlElement(name = "FirstName", required = true)
	protected String firstName;
	@XmlElement(name = "LastName", required = true)
	protected String lastName;
	@XmlElement(required = true)
	protected String city;
	@XmlElement(required = true)
	protected String country;

	/**
	 * Gets the value of the firstName property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Sets the value of the firstName property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setFirstName(final String value)
	{
		this.firstName = value;
	}

	/**
	 * Gets the value of the lastName property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Sets the value of the lastName property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setLastName(final String value)
	{
		this.lastName = value;
	}

	/**
	 * Gets the value of the city property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCity()
	{
		return city;
	}

	/**
	 * Sets the value of the city property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setCity(final String value)
	{
		this.city = value;
	}

	/**
	 * Gets the value of the country property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCountry()
	{
		return country;
	}

	/**
	 * Sets the value of the country property.
	 *
	 * @param value
	 *           allowed object is {@link String }
	 *
	 */
	public void setCountry(final String value)
	{
		this.country = value;
	}


	/*
	 * @Override public String toString() { return "Employee [firstName=" + firstName + ", lastName=" + lastName +
	 * ", city=" + city + ", country=" + country + "]"; }
	 */


}
